name: gislaine_studio
description: App de gestão de Gislaine Studio em Andradina.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.6.1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  awesome_dialog: ^2.1.2
  path_provider: ^2.0.11
  http: ^0.13.5
  path: ^1.8.1
  intl: ^0.17.0

  sqlite3_flutter_libs: ^0.5.0
  drift: ^2.0.2+1

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  drift_dev: ^2.0.2
  build_runner: ^2.2.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
